Wrappers hw
pikachuha111/TAF_AQA18 pull request #11
Opened 2023-02-06 10:08 UTC by pikachuha111

Wrappers hw

2023-02-07 13:57 UTC, wildpioneer requested changes

2023-02-07 13:57 UTC, wildpioneer commented on src/test/java/elements/CheckBox.java
> +        if (!uiElement.isSelected()) {
Строки 22, 23 дублируют строки 28, 29 - а следовательно это надо вынести в отдельный метод

2023-02-07 15:29 UTC, pikachuha111 commented on src/test/java/elements/CheckBox.java
> +        if (!uiElement.isSelected()) {
resolved and committed

2023-02-26 17:52 UTC, wildpioneer commented
Проверено

2023-02-26 17:52 UTC, closed without merging